import type { Metadata } from "next";
import "./globals.css";
import { openSans } from "@/components/ui/fonts";
import { Toaster } from "sonner";
import { ModalLandingPageProvider } from "@/components/modal-landing-page/modal-landing-page-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased`}>
        <Toaster position="top-center" richColors />
        {children}
        <ModalLandingPageProvider />
      </body>
    </html>
  );
}
